import type { Metadata } from "next";
import {
  inter,
  poppins,
  pacifico,
  yuji_mai,
  great_vibes,
} from "../components/fonts";
import "./globals.css";

import Footer from "@/components/Footer";
import ReduxProvider from "@/components/Cart/reduxprovider";
import SessionWrapper from "@/components/SessionWrapper";

export const metadata: Metadata = {
  title: "Ecommerce Web App Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          (inter.variable,
          poppins.variable,
          pacifico.variable,
          yuji_mai.variable,
          great_vibes.variable)
        }
      >
        {/* <Header /> */}
        <SessionWrapper>
          <ReduxProvider>{children}</ReduxProvider>
          <Footer />
        </SessionWrapper>
      </body>
    </html>
  );
}
