import type { Metadata } from "next";
import { inter, greatvibes } from "@/components/fonts";
import "./globals.css";
import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(inter.variable, greatvibes.variable)}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
